<?xml version="1.0" encoding="UTF-8" ?>
<Package name="test_igo3" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="test_igo/behavior_1" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="test_igo2/behavior_1" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="test_igo2/test_igo/behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="Sanya_4" src="html/Sanya_4.jpg" />
        <File name="test" src="html/test.jpg" />
        <File name="test2" src="html/test2.jpg" />
        <File name="8" src="html/8.jpg" />
        <File name="mig" src="html/mig.jpg" />
        <File name="style" src="html/css/style.css" />
        <File name="IMG_2152" src="html/testmov.mp4" />
        <File name="Sback" src="html/Sback.png" />
        <File name="Sback" src="html/css/Sback.png" />
        <File name="style2" src="html/css/style2.css" />
        <File name="test" src="html/test.html" />
        <File name="h_logo" src="html/h_logo.jpg" />
        <File name="IMG_2687" src="html/IMG_2687.JPG" />
        <File name="ALL" src="html/css/ALL.jpg" />
        <File name="topback" src="html/css/topback.jpg" />
        <File name="top" src="html/top.jpg" />
        <File name="logotypejp_mp_m_1.1" src="html/css/logotypejp_mp_m_1.1.ttf" />
        <File name="top2" src="html/css/top2.jpg" />
        <File name="Emain" src="html/css/Emain.jpg" />
        <File name="Smain" src="html/css/Smain.jpg" />
        <File name="1" src="html/1.PNG" />
        <File name="2" src="html/2.PNG" />
        <File name="3" src="html/3.PNG" />
        <File name="4" src="html/4.PNG" />
        <File name="5" src="html/5.PNG" />
        <File name="6" src="html/6.PNG" />
        <File name="7" src="html/7.PNG" />
        <File name="8" src="html/8.PNG" />
        <File name="9" src="html/9.PNG" />
        <File name="10" src="html/10.PNG" />
        <File name="11" src="html/11.PNG" />
        <File name="main" src="html/main.html" />
        <File name="index" src="html/index.html" />
        <File name="stylemain" src="html/css/stylemain.css" />
        <File name="main" src="html/main.jpg" />
        <File name="main" src="html/css/main.jpg" />
        <File name="1" src="test_igo/html/1.PNG" />
        <File name="10" src="test_igo/html/10.PNG" />
        <File name="11" src="test_igo/html/11.PNG" />
        <File name="2" src="test_igo/html/2.PNG" />
        <File name="3" src="test_igo/html/3.PNG" />
        <File name="4" src="test_igo/html/4.PNG" />
        <File name="5" src="test_igo/html/5.PNG" />
        <File name="6" src="test_igo/html/6.PNG" />
        <File name="7" src="test_igo/html/7.PNG" />
        <File name="8" src="test_igo/html/8.PNG" />
        <File name="8" src="test_igo/html/8.jpg" />
        <File name="9" src="test_igo/html/9.PNG" />
        <File name="IMG_2687" src="test_igo/html/IMG_2687.JPG" />
        <File name="Sanya_4" src="test_igo/html/Sanya_4.jpg" />
        <File name="Sback" src="test_igo/html/Sback.png" />
        <File name="ALL" src="test_igo/html/css/ALL.jpg" />
        <File name="Emain" src="test_igo/html/css/Emain.jpg" />
        <File name="Sback" src="test_igo/html/css/Sback.png" />
        <File name="Smain" src="test_igo/html/css/Smain.jpg" />
        <File name="logotypejp_mp_m_1.1" src="test_igo/html/css/logotypejp_mp_m_1.1.ttf" />
        <File name="main" src="test_igo/html/css/main.jpg" />
        <File name="style" src="test_igo/html/css/style.css" />
        <File name="style2" src="test_igo/html/css/style2.css" />
        <File name="stylemain" src="test_igo/html/css/stylemain.css" />
        <File name="top2" src="test_igo/html/css/top2.jpg" />
        <File name="topback" src="test_igo/html/css/topback.jpg" />
        <File name="h_logo" src="test_igo/html/h_logo.jpg" />
        <File name="index" src="test_igo/html/index.html" />
        <File name="main" src="test_igo/html/main.html" />
        <File name="main" src="test_igo/html/main.jpg" />
        <File name="mig" src="test_igo/html/mig.jpg" />
        <File name="test" src="test_igo/html/test.html" />
        <File name="test" src="test_igo/html/test.jpg" />
        <File name="test2" src="test_igo/html/test2.jpg" />
        <File name="testmov" src="test_igo/html/testmov.mp4" />
        <File name="top" src="test_igo/html/top.jpg" />
        <File name="manifest" src="test_igo/manifest.xml" />
        <File name="test_igo" src="test_igo/test_igo.pml" />
        <File name="seigyo" src="html/css/seigyo.css" />
        <File name="seigyo" src="html/seigyo.html" />
        <File name="twitter" src="html/twitter.html" />
        <File name="bang" src="html/bang.html" />
        <File name="bang" src="html/css/bang.css" />
        <File name="12" src="html/12.PNG" />
        <File name="tit" src="html/tit.png" />
        <File name="k1" src="html/k1.PNG" />
        <File name="k10" src="html/k10.PNG" />
        <File name="k11" src="html/k11.PNG" />
        <File name="k2" src="html/k2.PNG" />
        <File name="k3" src="html/k3.PNG" />
        <File name="k4" src="html/k4.PNG" />
        <File name="k5" src="html/k5.PNG" />
        <File name="k6" src="html/k6.PNG" />
        <File name="k7" src="html/k7.PNG" />
        <File name="k8" src="html/k8.PNG" />
        <File name="k9" src="html/k9.PNG" />
        <File name="1" src="test_igo2/html/1.PNG" />
        <File name="10" src="test_igo2/html/10.PNG" />
        <File name="11" src="test_igo2/html/11.PNG" />
        <File name="12" src="test_igo2/html/12.PNG" />
        <File name="2" src="test_igo2/html/2.PNG" />
        <File name="3" src="test_igo2/html/3.PNG" />
        <File name="4" src="test_igo2/html/4.PNG" />
        <File name="5" src="test_igo2/html/5.PNG" />
        <File name="6" src="test_igo2/html/6.PNG" />
        <File name="7" src="test_igo2/html/7.PNG" />
        <File name="8" src="test_igo2/html/8.PNG" />
        <File name="8" src="test_igo2/html/8.jpg" />
        <File name="9" src="test_igo2/html/9.PNG" />
        <File name="IMG_2687" src="test_igo2/html/IMG_2687.JPG" />
        <File name="Sanya_4" src="test_igo2/html/Sanya_4.jpg" />
        <File name="Sback" src="test_igo2/html/Sback.png" />
        <File name="bang" src="test_igo2/html/bang.html" />
        <File name="ALL" src="test_igo2/html/css/ALL.jpg" />
        <File name="Emain" src="test_igo2/html/css/Emain.jpg" />
        <File name="Sback" src="test_igo2/html/css/Sback.png" />
        <File name="Smain" src="test_igo2/html/css/Smain.jpg" />
        <File name="bang" src="test_igo2/html/css/bang.css" />
        <File name="logotypejp_mp_m_1.1" src="test_igo2/html/css/logotypejp_mp_m_1.1.ttf" />
        <File name="main" src="test_igo2/html/css/main.jpg" />
        <File name="seigyo" src="test_igo2/html/css/seigyo.css" />
        <File name="style" src="test_igo2/html/css/style.css" />
        <File name="style2" src="test_igo2/html/css/style2.css" />
        <File name="stylemain" src="test_igo2/html/css/stylemain.css" />
        <File name="top2" src="test_igo2/html/css/top2.jpg" />
        <File name="topback" src="test_igo2/html/css/topback.jpg" />
        <File name="h_logo" src="test_igo2/html/h_logo.jpg" />
        <File name="index" src="test_igo2/html/index.html" />
        <File name="k1" src="test_igo2/html/k1.PNG" />
        <File name="k10" src="test_igo2/html/k10.PNG" />
        <File name="k11" src="test_igo2/html/k11.PNG" />
        <File name="k2" src="test_igo2/html/k2.PNG" />
        <File name="k3" src="test_igo2/html/k3.PNG" />
        <File name="k4" src="test_igo2/html/k4.PNG" />
        <File name="k5" src="test_igo2/html/k5.PNG" />
        <File name="k6" src="test_igo2/html/k6.PNG" />
        <File name="k7" src="test_igo2/html/k7.PNG" />
        <File name="k8" src="test_igo2/html/k8.PNG" />
        <File name="k9" src="test_igo2/html/k9.PNG" />
        <File name="main" src="test_igo2/html/main.html" />
        <File name="main" src="test_igo2/html/main.jpg" />
        <File name="mig" src="test_igo2/html/mig.jpg" />
        <File name="seigyo" src="test_igo2/html/seigyo.html" />
        <File name="test" src="test_igo2/html/test.html" />
        <File name="test" src="test_igo2/html/test.jpg" />
        <File name="test2" src="test_igo2/html/test2.jpg" />
        <File name="testmov" src="test_igo2/html/testmov.mp4" />
        <File name="tit" src="test_igo2/html/tit.png" />
        <File name="top" src="test_igo2/html/top.jpg" />
        <File name="twitter" src="test_igo2/html/twitter.html" />
        <File name="manifest" src="test_igo2/manifest.xml" />
        <File name="1" src="test_igo2/test_igo/html/1.PNG" />
        <File name="10" src="test_igo2/test_igo/html/10.PNG" />
        <File name="11" src="test_igo2/test_igo/html/11.PNG" />
        <File name="2" src="test_igo2/test_igo/html/2.PNG" />
        <File name="3" src="test_igo2/test_igo/html/3.PNG" />
        <File name="4" src="test_igo2/test_igo/html/4.PNG" />
        <File name="5" src="test_igo2/test_igo/html/5.PNG" />
        <File name="6" src="test_igo2/test_igo/html/6.PNG" />
        <File name="7" src="test_igo2/test_igo/html/7.PNG" />
        <File name="8" src="test_igo2/test_igo/html/8.PNG" />
        <File name="8" src="test_igo2/test_igo/html/8.jpg" />
        <File name="9" src="test_igo2/test_igo/html/9.PNG" />
        <File name="IMG_2687" src="test_igo2/test_igo/html/IMG_2687.JPG" />
        <File name="Sanya_4" src="test_igo2/test_igo/html/Sanya_4.jpg" />
        <File name="Sback" src="test_igo2/test_igo/html/Sback.png" />
        <File name="ALL" src="test_igo2/test_igo/html/css/ALL.jpg" />
        <File name="Emain" src="test_igo2/test_igo/html/css/Emain.jpg" />
        <File name="Sback" src="test_igo2/test_igo/html/css/Sback.png" />
        <File name="Smain" src="test_igo2/test_igo/html/css/Smain.jpg" />
        <File name="logotypejp_mp_m_1.1" src="test_igo2/test_igo/html/css/logotypejp_mp_m_1.1.ttf" />
        <File name="main" src="test_igo2/test_igo/html/css/main.jpg" />
        <File name="style" src="test_igo2/test_igo/html/css/style.css" />
        <File name="style2" src="test_igo2/test_igo/html/css/style2.css" />
        <File name="stylemain" src="test_igo2/test_igo/html/css/stylemain.css" />
        <File name="top2" src="test_igo2/test_igo/html/css/top2.jpg" />
        <File name="topback" src="test_igo2/test_igo/html/css/topback.jpg" />
        <File name="h_logo" src="test_igo2/test_igo/html/h_logo.jpg" />
        <File name="index" src="test_igo2/test_igo/html/index.html" />
        <File name="main" src="test_igo2/test_igo/html/main.html" />
        <File name="main" src="test_igo2/test_igo/html/main.jpg" />
        <File name="mig" src="test_igo2/test_igo/html/mig.jpg" />
        <File name="test" src="test_igo2/test_igo/html/test.html" />
        <File name="test" src="test_igo2/test_igo/html/test.jpg" />
        <File name="test2" src="test_igo2/test_igo/html/test2.jpg" />
        <File name="testmov" src="test_igo2/test_igo/html/testmov.mp4" />
        <File name="top" src="test_igo2/test_igo/html/top.jpg" />
        <File name="manifest" src="test_igo2/test_igo/manifest.xml" />
        <File name="test_igo" src="test_igo2/test_igo/test_igo.pml" />
        <File name="test_igo2" src="test_igo2/test_igo2.pml" />
        <File name="スライド10" src="html/スライド10.PNG" />
        <File name="スライド11" src="html/スライド11.PNG" />
        <File name="c1" src="html/c1.PNG" />
        <File name="c10" src="html/c10.PNG" />
        <File name="c11" src="html/c11.PNG" />
        <File name="c12" src="html/c12.PNG" />
        <File name="c13" src="html/c13.PNG" />
        <File name="c14" src="html/c14.PNG" />
        <File name="c2" src="html/c2.PNG" />
        <File name="c3" src="html/c3.PNG" />
        <File name="c4" src="html/c4.PNG" />
        <File name="c5" src="html/c5.PNG" />
        <File name="c6" src="html/c6.PNG" />
        <File name="c7" src="html/c7.PNG" />
        <File name="c8" src="html/c8.PNG" />
        <File name="c9" src="html/c9.PNG" />
        <File name="スライド15" src="html/スライド15.PNG" />
        <File name="スライド16" src="html/スライド16.PNG" />
        <File name="bangg" src="html/bangg.JPG" />
        <File name="ex" src="html/ex.png" />
        <File name="gazo" src="html/css/gazo.jpg" />
        <File name="hkkaiiw" src="html/css/hkkaiiw.ttf" />
        <File name="hkkaiiw" src="html/hkkaiiw.ttf" />
        <File name="emblem" src="html/emblem.jpg" />
        <File name="d1" src="html/d1.PNG" />
        <File name="d10" src="html/d10.PNG" />
        <File name="d11" src="html/d11.PNG" />
        <File name="d2" src="html/d2.PNG" />
        <File name="d3" src="html/d3.PNG" />
        <File name="d4" src="html/d4.PNG" />
        <File name="d5" src="html/d5.PNG" />
        <File name="d6" src="html/d6.PNG" />
        <File name="d7" src="html/d7.PNG" />
        <File name="d8" src="html/d8.PNG" />
        <File name="d9" src="html/d9.PNG" />
        <File name="song" src="html/song.wma" />
        <File name="me" src="html/me.png" />
        <File name="bgm" src="html/bgm.mp3" />
        <File name="song" src="html/song.png" />
        <File name="icon" src="icon.png" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src="test_igo2/test_igo/.metadata" />
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
